"""Tableaux des fascicules « applications » imprimés en image dans les PDF officiels (Q32).

Les valeurs ont été transcrites et relues sur deux rendus agrandis (échelles 1,3 et 2,6) ; elles
passent les mêmes contrôles automatiques que les tableaux lus dans le texte (plages, monotonie)
et restent marquées « lu sur image » avec leur page. Les cellules sont écrites comme dans le
document : « 0,51 (0,47) » = valeur (variante entre parenthèses), « – » = case sans valeur.
Les libellés des lignes décrivent les schémas du document, sans les reproduire.
"""
from __future__ import annotations

PARASISMIQUE = "Joint vertical rempli de mortier (application parasismique)"

TRANSCRITS: list[dict] = [
    {
        "id": "murs-T1",
        "fascicule": "murs",
        "numero": 1,
        "page": 2,
        "section": "1.1.1.2",
        "titre": "Briques pleines de terre cuite (format courant 6 × 10,5 × 22 cm)",
        "famille": "terre_cuite",
        "axe_lignes": "Appareillage (schéma p. 2)",
        "axe_colonnes": "Épaisseur E de l'élément (cm)",
        "colonnes": ["6", "10,5", "22", "33,5", "45"],
        "lignes": [
            ("Appareillage 1", ["0,06", "0,12", "", "", ""]),
            ("Appareillage 2", ["", "", "0,22", "", ""]),
            ("Appareillage 3", ["", "", "", "0,32", ""]),
            ("Appareillage 4", ["", "", "", "", "0,44"]),
        ],
        "monotonie": {"colonnes": "croissant"},
    },
    {
        "id": "murs-T4",
        "fascicule": "murs",
        "numero": 4,
        "page": 5,
        "section": "1.1.2.1.2",
        "titre": "Briques à perforations verticales de format moyen",
        "famille": "terre_cuite",
        "axe_lignes": "Brique (schéma p. 5)",
        "axe_colonnes": "Épaisseur E de l'élément (cm)",
        "colonnes": ["15", "20", "25"],
        "lignes": [
            ("Brique 1", ["0,33", "", ""]),
            ("Brique 2", ["", "0,51 (0,47)", ""]),
            ("Brique 3", ["", "0,46 (0,42)", ""]),
            ("Brique 4", ["", "", "0,56 (0,52)"]),
        ],
        "variante": PARASISMIQUE,
        "monotonie": {"colonnes": "croissant"},
    },
    {
        "id": "murs-T5",
        "fascicule": "murs",
        "numero": 5,
        "page": 6,
        "section": "1.1.2.2",
        "titre": "Briques à perforations horizontales (briques classiques)",
        "famille": "terre_cuite",
        "axe_lignes": "Brique (schéma p. 6)",
        "axe_colonnes": "Épaisseur E de l'élément (cm)",
        "colonnes": ["3,5", "4", "5", "7,5", "10", "15", "20", "22,5", "25", "27"],
        "lignes": [
            ("Brique 1", ["0,08", "0,09", "0,11", "", "", "", "", "", "", ""]),
            ("Brique 2", ["", "", "0,16", "0,21", "0,24", "", "", "", "", ""]),
            ("Planelle", ["", "", "0,24", "0,24", "", "", "", "", "", ""]),
            ("Brique 4", ["", "", "", "", "", "0,35", "", "", "", ""]),
            ("Brique 5", ["", "", "", "", "", "", "0,5 (0,45)", "", "", ""]),
            ("Brique 6", ["", "", "", "", "", "", "0,47 (0,44)", "", "", ""]),
            ("Brique 7", ["", "", "", "", "", "", "0,56", "0,60", "0,63", "0,65"]),
        ],
        "variante": "Joint vertical rempli de mortier",
        "remarques": ["Planelle : une seule case fusionnée couvre les épaisseurs 5 et 7,5 cm."],
        "monotonie": {"colonnes": "croissant"},
    },
    {
        "id": "murs-T6",
        "fascicule": "murs",
        "numero": 6,
        "page": 7,
        "section": "1.1.2.2",
        "titre": "Briques à perforations horizontales de type G",
        "famille": "terre_cuite",
        "axe_lignes": "Brique (schéma p. 7)",
        "axe_colonnes": "Épaisseur E de l'élément (cm)",
        "colonnes": ["20", "27", "30"],
        "lignes": [
            ("Brique G 1", ["0,67 (0,63)", "", ""]),
            ("Brique G 2", ["", "0,84 (0,80)", ""]),
            ("Brique G 3", ["", "", "0,86 (0,81)"]),
            ("Brique G 4", ["", "", "1,00 (0,95)"]),
        ],
        "variante": PARASISMIQUE,
        "monotonie": {"colonnes": "croissant"},
    },
    {
        "id": "murs-T8",
        "fascicule": "murs",
        "numero": 8,
        "page": 9,
        "section": "1.2.2",
        "titre": "Blocs creux en béton de granulats courants (NF EN 771-3)",
        "famille": "beton",
        "axe_lignes": "Bloc (dimensions de coordination modulaire, cm)",
        "axe_colonnes": "Résistance thermique",
        "colonnes": ["R"],
        "cles": ["Épaisseur (cm)", "Hauteur (cm)", "Rangées d'alvéoles", "Montage"],
        "lignes": [
            ("5 × 20 × 50", ["0,07"], ["5", "19", "1", "joints traditionnels"]),
            ("7,5 × 20 × 50", ["0,10"], ["7,5", "19", "1", "joints traditionnels"]),
            ("10 × 20 × 50", ["0,12"], ["10", "19", "1", "joints traditionnels"]),
            ("12,5 × 20 × 50", ["0,13"], ["12,5", "19", "1", "joints traditionnels"]),
            ("15 × 20 × 50, une rangée", ["0,14"], ["15", "19", "1", "joints traditionnels"]),
            ("15 × 25 × 50, une rangée", ["0,14"], ["15", "24", "1", "joints traditionnels"]),
            ("15 × 20 × 50, deux rangées", ["0,18"], ["15", "19", "2", "joints traditionnels"]),
            ("15 × 25 × 50, deux rangées", ["0,18"], ["15", "24", "2", "joints traditionnels"]),
            ("17,5 × 20 × 50", ["0,21"], ["17,5", "19", "2", "joints traditionnels"]),
            ("20 × 20 × 50, deux rangées", ["0,23 (0,21)"], ["20", "19", "2", "joints traditionnels"]),
            ("20 × 25 × 50, deux rangées", ["0,23 (0,21)"], ["20", "24", "2", "joints traditionnels"]),
            ("20 × 20 × 50, trois rangées", ["0,29 (0,26)"], ["20", "19", "3", "joints traditionnels"]),
            ("22,5 × 20 × 50", ["0,24"], ["22,5", "19", "2", "joints traditionnels"]),
            ("25 × 20 × 50", ["0,32 (0,28)"], ["25", "19", "3", "joints traditionnels"]),
            ("27,5 × 20 × 50", ["0,34 (0,30)"], ["27,5", "19", "3", "joints traditionnels"]),
            # Note * sous le tableau (texte de la page) : blocs de 20 cm à deux rangées d'alvéoles.
            ("20 cm deux rangées, joints minces (≤ 2 mm), avec voiles de pose", ["0,27 (0,26)"], ["20", "19 ou 24", "2", "joints minces"]),
            ("20 cm deux rangées, joints minces (≤ 2 mm), sans voiles de pose", ["0,28 (0,27)"], ["20", "19 ou 24", "2", "joints minces"]),
        ],
        "variante": "Joint central rempli de mortier (application parasismique)",
        "remarques": [
            "Joints minces : blocs marqués NF destinés à la pose collée (lettre « C ») et mortier sous "
            "évaluation technique (Avis Technique, DTA, certification).",
        ],
        "monotonie": {"epaisseur": "Épaisseur (cm)", "groupes": ["Rangées d'alvéoles", "Montage"]},
        # Les deux lignes « joints minces » viennent du texte de la page : recoupées à chaque construction.
        "verifier_texte": ["0,27 (0.26) K.m²/W pour des blocs avec voiles", "0,28 (0,27) K.m²/W pour les blocs sans voiles"],
    },
    {
        "id": "murs-F3",
        "fascicule": "murs",
        "numero": None,
        "page": 3,
        "section": "1.1.1.4",
        "titre": "Blocs perforés de terre cuite (format courant 6 × 22 × 22 cm, figure 3)",
        "famille": "terre_cuite",
        "lecture": "texte",
        "axe_lignes": "Bloc (figure 3 p. 3)",
        "axe_colonnes": "Résistance thermique",
        "colonnes": ["R"],
        "lignes": [
            ("8 rangées d'alvéoles", ["0,38"]),
            ("7 rangées d'alvéoles", ["0,33"]),
        ],
        "verifier_texte": ["8 rangées d'alvéoles : 7 rangées d'alvéoles :\nR = 0,38 m2.K/W R = 0,33 m2.K/W"],
    },
    {
        "id": "planchers-T16",
        "fascicule": "planchers",
        "numero": 16,
        "page": 19,
        "section": "3",
        "titre": "Dalles alvéolées à base de granulats courants (NF EN 1168)",
        "famille": "plancher_beton",
        "axe_lignes": "e / l : cloison interne mini sur largeur de l'alvéole",
        "axe_colonnes": "Épaisseur E du plancher (cm)",
        "colonnes": ["15", "20", "25", "30", "35", "40"],
        "lignes": [
            ("e/l ≤ 0,3", ["0,16", "0,18", "0,20", "0,22", "0,24", "0,27"]),
            ("0,3 < e/l ≤ 0,5", ["–", "0,16", "0,18", "0,20", "0,22", "0,25"]),
            ("0,5 < e/l < 1,0", ["–", "–", "0,15", "0,17", "0,19", "0,21"]),
        ],
        "remarques": ["Note du document : des valeurs intermédiaires peuvent être obtenues par interpolation linéaire."],
        "monotonie": {"colonnes": "croissant", "lignes": "decroissant"},
    },
    {
        "id": "cloisons-T5",
        "fascicule": "cloisons",
        "numero": 5,
        "page": 2,
        "section": "1.5",
        "titre": "Panneaux de particules de bois extrudé (rangée d'alvéoles parallèle aux faces)",
        "famille": "cloison",
        "axe_lignes": "Coupe du panneau alvéolé (schéma p. 2)",
        "axe_colonnes": "Résistance thermique",
        "colonnes": ["R"],
        "cles": ["Épaisseur (cm)"],
        "lignes": [
            ("Alvéoles Ø 1,6 cm, épaisseur 3 cm", ["0,16"], ["3"]),
            ("Alvéoles Ø 2,1 cm, épaisseur 3,5 cm", ["0,18"], ["3,5"]),
            ("Alvéoles Ø 3,0 cm, épaisseur 5 cm", ["0,23"], ["5"]),
            ("Alvéoles Ø 4,8 cm, épaisseur 7 cm", ["0,31"], ["7"]),
        ],
        "monotonie": {"epaisseur": "Épaisseur (cm)"},
    },
]
