import type { AccountingMatrixSummary, InvoiceDecision } from "./invoices.types";
export const invoicesMock: InvoiceDecision[] = [
  { stableId: "mock:TG-88412", source: "mock", sourceId: "TG-88412", supplier: "TotalEnergies", invoiceNumber: "TG-88412", siteLabel: "École des Beaux-Arts", contractLabel: "Gaz · Lot 7", amountTtc: 8742.18, amountTtcLabel: "8 742,18 €", issuedAt: "22 juin 2026", dueAt: "02 juillet 2026", status: "anomalie", matrixStatus: "a_completer", issue: "CTA supérieure de 126,40 € à la référence", alreadyProcessed: false, snapshotVersionLabel: "Référentiels gaz datés", proofs: [{ label: "CTA", method: "Écart à expliquer", status: "warn", reference: "Barème gaz" }] },
  { stableId: "mock:EN-260621-18", source: "mock", sourceId: "EN-260621-18", supplier: "ENGIE", invoiceNumber: "EN-260621-18", siteLabel: "Hôtel de Ville", contractLabel: "Électricité · Lot 1", amountTtc: 12408.72, amountTtcLabel: "12 408,72 €", issuedAt: "21 juin 2026", dueAt: "01 juillet 2026", status: "decision", matrixStatus: "proposee", issue: "Contrôles conformes, décision attendue", alreadyProcessed: false, snapshotVersionLabel: "Matrice ENGIE V3", proofs: [{ label: "BPU", method: "Prix unitaires conformes", status: "ok" }] },
  { stableId: "mock:EDF-784521", source: "mock", sourceId: "EDF-784521", supplier: "EDF", invoiceNumber: "EDF-784521", siteLabel: "Éclairage public · Secteur 3", contractLabel: "Électricité · Voirie", amountTtc: 24816.09, amountTtcLabel: "24 816,09 €", issuedAt: "20 juin 2026", dueAt: "30 juin 2026", status: "conforme", matrixStatus: "validee", issue: "Aucun écart significatif", alreadyProcessed: true, snapshotVersionLabel: "Matrice EDF V2", proofs: [{ label: "TURPE", method: "Référentiel daté vérifié", status: "ok" }] },
  { stableId: "mock:DK-2026-0618", source: "mock", sourceId: "DK-2026-0618", supplier: "DALKIA", invoiceNumber: "DK-2026-0618", siteLabel: "Centre sportif Fonquerne", contractLabel: "CPE · P1", amountTtc: 38125.40, amountTtcLabel: "38 125,40 €", issuedAt: "18 juin 2026", dueAt: "05 juillet 2026", status: "decision", matrixStatus: "a_arbitrer", issue: "Cible et DJU vérifiés, ventilation P1 à confirmer", alreadyProcessed: false, snapshotVersionLabel: "Matrice DALKIA projet", proofs: [{ label: "P1", method: "Cible et DJU vérifiés", status: "warn" }] },
];
export const accountingMatricesMock: AccountingMatrixSummary[] = [
  { id: "engie-l1", supplier: "ENGIE", contract: "Électricité · Lot 1", version: "V3 · 01/01/2026", status: "Active", coverage: "96 %", rules: "18 règles", exceptions: "2 à compléter" },
  { id: "edf-voirie", supplier: "EDF", contract: "Électricité · Voirie", version: "V2 · 01/01/2026", status: "Active", coverage: "100 %", rules: "9 règles", exceptions: "Aucune" },
  { id: "total-l7", supplier: "TotalEnergies", contract: "Gaz · Lot 7", version: "V1 · 01/01/2026", status: "À valider", coverage: "84 %", rules: "12 règles", exceptions: "4 à compléter" },
  { id: "dalkia-cpe", supplier: "DALKIA", contract: "CPE · P1/P2/P3", version: "Projet · 2026", status: "Incomplète", coverage: "68 %", rules: "43 couples", exceptions: "9 arbitrages" },
];
