import { useMemo, useState } from "react";
import { Card, DataTable, FilterBar, KpiCard, StatusBadge } from "../../design-system";
import { fluidDriftsMock, fluidKpisMock, subscriptionAnalysesMock } from "./fluids.mock";
import type { FluidAlertTone } from "./fluids.types";

function tone(tone: FluidAlertTone) { return tone === "bad" ? "bad" : tone === "warn" ? "warn" : tone === "ok" ? "ok" : "info"; }
export function FluidsPortfolioPageV1() {
  const [query, setQuery] = useState("");
  const rows = useMemo(() => { const q = query.trim().toLowerCase(); return q ? subscriptionAnalysesMock.filter((row) => Object.values(row).join(" ").toLowerCase().includes(q)) : subscriptionAnalysesMock; }, [query]);
  return <div className="po2-page-v1"><header className="po2-page-v1__head"><span className="po2-eyebrow">Fluides</span><h1>Consommations, DJU, atterrissage et abonnements.</h1><p>La V1 distingue les distributeurs de mesure (ENEDIS, GRDF, eau) des fournisseurs et contrats (EDF, ENGIE, TotalEnergies, futurs titulaires eau).</p></header><div className="po2-kpi-grid">{fluidKpisMock.map((kpi) => <KpiCard key={kpi.label} label={kpi.label} value={kpi.value} detail={kpi.detail} trend={kpi.trend} tone={kpi.tone === "bad" ? "danger" : kpi.tone === "warn" ? "warning" : "neutral"} />)}</div><div className="po2-two-columns"><Card title="Dérives prioritaires" eyebrow="Signaux"><div className="po2-decision-list">{fluidDriftsMock.map((drift) => <article key={drift.rank} className="po2-decision-item"><StatusBadge tone={tone(drift.tone)}>{String(drift.rank)}</StatusBadge><div><strong>{drift.label}</strong><small>{drift.site} · preuve : {drift.proof}</small></div><b>{drift.impact}</b></article>)}</div></Card><Card title="Atterrissage annuel" eyebrow="Prévision"><div className="po2-forecast-card"><strong>2,94 M€</strong><span>Scénario central · fourchette 2,86–3,08 M€</span><p>Réalisé distributeurs + reste estimé, valorisé avec éléments de facturation et prix contractuels.</p></div></Card></div><Card title="Abonnements à recalibrer" eyebrow="Contrats"><FilterBar searchPlaceholder="Site, compteur, fournisseur" searchValue={query} onSearchChange={setQuery} /><DataTable rows={rows} getRowKey={(row) => row.id} columns={[{ key: "site", header: "Site / compteur", render: (row) => <span><strong>{row.site}</strong><small className="po2-muted-line">{row.source} · {row.meter}</small></span> }, { key: "contract", header: "Fournisseur", render: (row) => row.supplier }, { key: "current", header: "Actuel", render: (row) => row.current }, { key: "target", header: "Recommandation", render: (row) => <strong>{row.recommendation}</strong> }, { key: "diagnostic", header: "Diagnostic", render: (row) => <StatusBadge tone={tone(row.tone)}>{row.diagnostic}</StatusBadge> }, { key: "gain", header: "Potentiel", render: (row) => row.potential }]} /></Card></div>;
}
