import { useMemo, useState } from "react";
import { Card, DataTable, FilterBar, KpiCard, StatusBadge } from "../../design-system";
import { siteDecisionsMock, sitesMock } from "./sites.mock";
import type { Site360 } from "./sites.types";

export function SitesPortfolioPageV1() {
  const [query, setQuery] = useState("");
  const [selectedSite, setSelectedSite] = useState<Site360>(sitesMock[0]);
  const rows = useMemo(() => { const q = query.trim().toLowerCase(); return q ? sitesMock.filter((site) => Object.values(site).join(" ").toLowerCase().includes(q)) : sitesMock; }, [query]);
  return <div className="po2-page-v1"><header className="po2-page-v1__head"><span className="po2-eyebrow">Sites 360°</span><h1>Le site comme porte d’entrée.</h1><p>Une fiche transversale pour comprendre patrimoine, fluides, contrats, technique, budget et décisions reliées.</p></header><div className="po2-kpi-grid"><KpiCard label="Sites" value="118" detail="203 bâtiments" /><KpiCard label="Qualité fiable" value="92 %" detail="109 sites · 9 à fiabiliser" /><KpiCard label="Sites à surveiller" value="8" detail="couverture ou données" tone="warning" /><KpiCard label="Budget analysé" value="8,42 M€" detail="par opération et antenne" /></div><div className="po2-two-columns po2-sites-layout"><Card title="Portefeuille sites" eyebrow="Patrimoine"><FilterBar searchPlaceholder="Nom, adresse, usage" searchValue={query} onSearchChange={setQuery} /><DataTable rows={rows} getRowKey={(site) => site.id} onRowClick={setSelectedSite} columns={[{ key: "name", header: "Site", render: (site) => <span><strong>{site.name}</strong><small className="po2-muted-line">{site.address}</small></span> }, { key: "usage", header: "Usage", render: (site) => site.usage }, { key: "quality", header: "Qualité", render: (site) => <StatusBadge tone={parseInt(site.quality, 10) >= 95 ? "ok" : "warn"}>{site.quality}</StatusBadge> }, { key: "budget", header: "Budget", render: (site) => site.budget }, { key: "critical", header: "Critiques", render: (site) => <strong>{site.critical}</strong> }]} /></Card><Card title={selectedSite.name} eyebrow="Fiche site"><div className="po2-site-summary"><p>{selectedSite.address}</p><div className="po2-kpi-grid"><KpiCard label="Budget" value={selectedSite.budget} detail="opération active" /><KpiCard label="Fluides" value={selectedSite.energy} detail={selectedSite.meters} /><KpiCard label="Équipements" value={selectedSite.equipment} detail={`${selectedSite.critical} critiques`} /></div><div className="po2-decision-list">{siteDecisionsMock.map((decision) => <article key={decision.label} className="po2-decision-item"><StatusBadge tone={decision.tone}>{decision.label}</StatusBadge><div><strong>{decision.value}</strong><small>Preuve : {decision.proof}</small></div></article>)}</div></div></Card></div></div>;
}
